services:
  database:
    image: postgres:16.3
    container_name: yorlink-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
