apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorlink-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yorlink-backend
  template:
    metadata:
      labels:
        app: yorlink-backend
    spec:
      containers:
        - name: backend
          image: chanathipcha24/yorlink-backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: POSTGRES_HOST
            - name: APP_CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: APP_CORS_ALLOWED_ORIGINS
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: yorlink-backend-env
                  key: POSTGRES_PORT
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: yorlink-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
